name: Publish www

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm run test:smoke

      - name: Cleanup stale deployments
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ./public_html && rm -r _next

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: ${{ secrets.SOURCE }}
          TARGET: ${{ secrets.TARGET }}
