name: Publish .me

on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "src/**"
      - "ops/**"
      - "public/**"
      - "storage/en/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Setup build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run test
      - run: npm run build:en
      - run: npm run test:smoke

      - name: Cleanup stale deployments
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER_ME }}
          host: ${{ secrets.REMOTE_HOST_ME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_ME }}
          script: cd ./public_html && rm -r _next

      - name: Deploy
        uses: milanmk/actions-file-deployer@1.10
        with:
          remote-host: ${{ secrets.REMOTE_HOST_ME }}
          remote-user: ${{ secrets.REMOTE_USER_ME }}
          remote-password: ${{ secrets.DEPLOY_PASSWORD_ME }}
          remote-protocol: ${{ secrets.DEPLOY_PROTOCOL_ME }}
          local-path: ${{ secrets.SOURCE_ME }}
          remote-path: ${{ secrets.TARGET_ME }}
